### ISSUE TITLE
https://github.com/GoogleChrome/related-website-sets/issues/458#issue-2390012009

### ISSUE THREAD

**Issue by Roddy8720** [waylau/github-help#18]
https://github.com/GoogleChrome/related-website-sets/issues/460

**Comment by emailandxu** [comment]
您的邮件我尽力在12小时内处理。I'll be responding within 12 hours.

**Comment by ElevenEve** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Roddy8720** [comment]
> https://github.com/GoogleChrome/related-website-sets/issues/460

https://github.com/GoogleChrome/related-website-sets/issues/458#issue-2390012009

**Comment by emailandxu** [comment]
您的邮件我尽力在12小时内处理。I'll be responding within 12 hours.

**Comment by ElevenEve** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
