### ISSUE TITLE
为什么不做一张Pages来显示整个帮助目录呢？

### ISSUE THREAD

**Issue by DannyVim** [waylau/github-help#5]

**Comment by waylau** [comment]
@DannyVim  

1.README.md 就是 项目的目录

2.README.md里面列出的是所有已经翻译过的文章。

3.由于官方的 help 文章动态，即有可能增加或者删除文章，所以无法事先将所有的文章目录都列出来，也没有必要。

4.我翻译是按照一定的优先级来翻译的 ，优先级高的先翻译（也是大家可能会经常出问题的地方，先做翻译）
